<?php
/*
 * @author    Ivan Belchev <ivan@imbelchev.com>
 * @copyright Copyright (c) 2022 MIT (see LICENSE.md)
 * @link      https://imbelchev.com
 */
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Convert\Blog\ViewModel\PostDataProvider $dataProvider
 */
$dataProvider = $block->getData('DataProvider');
$postCard = $block->getChildBlock('post_card');
?>
<?php foreach($dataProvider->getAllPosts() as $post): ?>
    <?php $postCard->setData('post', $post) ?>
    <?= $block->getChildHtml('post_card', false) ?>
<?php endforeach; ?>
